### ISSUE TITLE
Submission to JCenter, maven-central?

### ISSUE THREAD

**Issue by andrew-charles** [rocketraman/kpropmap#1]
Is this going to be submitted to JCenter or mcentral as a library?

**Comment by rocketraman** [comment]
So far I wasn't aware anyone found it useful :-) I'm on vacation now but will look into submitting it when I'm back.

**Comment by rocketraman** [comment]
Started the process here: https://issues.sonatype.org/browse/OSSRH-57203

**Comment by rocketraman** [comment]
Published on jcenter: https://bintray.com/bintray/jcenter?filterByPkgName=kpropmap.

Publishing on maven central is pending.

**Comment by rocketraman** [comment]
And published on maven central also: https://repo1.maven.org/maven2/com/github/rocketraman/kpropmap/0.0.2/.
